// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function firstInPair(param) {
  return param[0];
}

function secondInPair(param) {
  return param[1];
}

var center = [
  960,
  540
];

var leroy = [
  "Xavier",
  "Leroy"
];

var coords = [
  101.5,
  42.3
];

exports.center = center;
exports.leroy = leroy;
exports.coords = coords;
exports.firstInPair = firstInPair;
exports.secondInPair = secondInPair;
/* No side effect */
